// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"Yattask/internal/controller/taskcontrollers"
	"Yattask/internal/controller/usercontrollers"
	"Yattask/internal/repository/tagrepositories"
	"Yattask/internal/repository/taskrepositories"
	"Yattask/internal/repository/userrepositories"
	"Yattask/internal/service/taskservices"
	"Yattask/internal/service/userservices"
	"github.com/go-playground/validator/v10"
	"gorm.io/gorm"
)

// Injectors from injector.go:

func InitializeUserControllers(db *gorm.DB, validation *validator.Validate) usercontrollers.UserController {
	userRepository := userrepositories.NewUserRepository()
	userService := userservices.NewUserService(db, userRepository, validation)
	userController := usercontrollers.NewUserController(userService)
	return userController
}

func InitializeTaskControllers(db *gorm.DB, validation *validator.Validate) taskcontrollers.TaskController {
	taskRepository := taskrepositories.NewTaskRepository()
	tagRepository := tagrepositories.NewTagRepository()
	taskService := taskservices.NewTaskService(db, taskRepository, tagRepository, validation)
	taskController := taskcontrollers.NewTaskController(taskService)
	return taskController
}
